## config.yml
host: localhost

mysql_user: root

mysql_root_password: 1234

db_user: chydycodes

user_pass: 1234

db_name: chydycodesdb

http_port: "80"

https_port: "443"

ssh_port: "22"

mysql_port: "3306"

certbot_site_name: "cynthiaezenwa.me"

certbot_package: "python3-certbot-apache"

certbot_plugin: "apache"

certbot_mail_address: chydycodes@gmail.com

